name: Deploy to B2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Upload files to B2
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          SOURCE_DIR: '.'
          DEST_BUCKET: ${{ secrets.B2_BUCKET_ID }}
          DEST_PATH: '/'
          AWS_S3_ENDPOINT: 'https://s3.us-west-002.backblazeb2.com'
          AWS_ACCESS_KEY_ID: ${{ secrets.B2_APPLICATION_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.B2_APPLICATION_KEY }}
